In [2]:
import numpy as np
import os
os.environ["KERAS_BACKEND"] = "tensorflow"
import keras
# source Gradioexp/bin/activate  for terminal activation

In [3]:

# Load the data and split it between train and test sets
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Scale images to the [0, 1] range
x_train = x_train.astype("float32") / 255
x_test = x_test.astype("float32") / 255
# Make sure images have shape (28, 28, 1)
x_train = np.expand_dims(x_train, -1)
x_test = np.expand_dims(x_test, -1)
print("x_train shape:", x_train.shape)
print("y_train shape:", y_train.shape)
print(x_train.shape[0], "train samples")
print(x_test.shape[0], "test samples")


x_train shape: (60000, 28, 28, 1)
y_train shape: (60000,)
60000 train samples
10000 test samples


In [4]:
# Model parameters
num_classes = 10
input_shape = (28, 28, 1)

In [5]:
model = keras.Sequential(
    [
        keras.layers.Input(shape=input_shape),
        keras.layers.Flatten(),
        keras.layers.Dense(256, activation="relu"),
        keras.layers.Dropout(0.2),
        keras.layers.Dense(128, activation="relu"),
        keras.layers.Dropout(0.2),
        keras.layers.Dense(num_classes, activation="softmax"),
    ]
)

In [ ]:
# model = keras.Sequential(
#     [
#         keras.layers.Input(shape=input_shape),
#         keras.layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
#         keras.layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
#         keras.layers.MaxPooling2D(pool_size=(2, 2)),
#         keras.layers.Conv2D(128, kernel_size=(3, 3), activation="relu"),
#         keras.layers.Conv2D(128, kernel_size=(3, 3), activation="relu"),
#         keras.layers.GlobalAveragePooling2D(),
#         keras.layers.Dropout(0.5),
#         keras.layers.Dense(num_classes, activation="softmax"),
#     ]
# )


In [15]:
model.summary()


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 26, 26, 64)     │           640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 24, 24, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 12, 12, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 10, 10, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 8, 8, 128)      │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d        │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 260,298 (1016.79 KB)

 Trainable params: 260,298 (1016.79 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(),
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    metrics=[
        keras.metrics.SparseCategoricalAccuracy(name="acc"),
    ],
)


In [17]:
batch_size = 128
epochs = 20

callbacks = [
    keras.callbacks.ModelCheckpoint(filepath="model_at_epoch_{epoch}.keras"),
    keras.callbacks.EarlyStopping(monitor="val_loss", patience=2),
]

model.fit(
    x_train,
    y_train,
    batch_size=batch_size,
    epochs=epochs,
    validation_split=0.15,
    callbacks=callbacks,
)
score = model.evaluate(x_test, y_test, verbose=0)


Epoch 1/20
399/399 ━━━━━━━━━━━━━━━━━━━━ 45s 111ms/step - acc: 0.7553 - loss: 0.7274 - val_acc: 0.9624 - val_loss: 0.1315
Epoch 2/20
399/399 ━━━━━━━━━━━━━━━━━━━━ 42s 105ms/step - acc: 0.9365 - loss: 0.2126 - val_acc: 0.9788 - val_loss: 0.0730
Epoch 3/20
399/399 ━━━━━━━━━━━━━━━━━━━━ 42s 105ms/step - acc: 0.9564 - loss: 0.1473 - val_acc: 0.9812 - val_loss: 0.0652
Epoch 4/20
399/399 ━━━━━━━━━━━━━━━━━━━━ 45s 112ms/step - acc: 0.9635 - loss: 0.1210 - val_acc: 0.9796 - val_loss: 0.0731
Epoch 5/20
399/399 ━━━━━━━━━━━━━━━━━━━━ 43s 108ms/step - acc: 0.9697 - loss: 0.1029 - val_acc: 0.9861 - val_loss: 0.0440
Epoch 6/20
399/399 ━━━━━━━━━━━━━━━━━━━━ 42s 105ms/step - acc: 0.9731 - loss: 0.0908 - val_acc: 0.9868 - val_loss: 0.0432
Epoch 7/20
399/399 ━━━━━━━━━━━━━━━━━━━━ 42s 106ms/step - acc: 0.9765 - loss: 0.0820 - val_acc: 0.9893 - val_loss: 0.0398
Epoch 8/20
399/399 ━━━━━━━━━━━━━━━━━━━━ 42s 106ms/step - acc: 0.9786 - loss: 0.0732 - val_acc: 0.9877 - val_loss: 0.0435
Epoch 9/20
399/399 ━━━━━━━━━━━━━

In [18]:
model.save("final_model.keras")


In [19]:
model = keras.saving.load_model("final_model.keras")


In [20]:
predictions = model.predict(x_test)


313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step


In [21]:
y_pred = np.argmax(predictions, axis=1)

In [22]:
accuracy = np.mean(y_pred == y_test)
print(f"Accuracy: {accuracy*100.:.4f}")

Accuracy: 99.3000


In [23]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, y_pred, digits=4))
cm = confusion_matrix(y_test, y_pred)

              precision    recall  f1-score   support

           0     0.9959    0.9969    0.9964       980
           1     0.9921    0.9965    0.9943      1135
           2     0.9913    0.9932    0.9923      1032
           3     0.9960    0.9941    0.9950      1010
           4     0.9939    0.9959    0.9949       982
           5     0.9888    0.9922    0.9905       892
           6     0.9906    0.9916    0.9911       958
           7     0.9970    0.9844    0.9907      1028
           8     0.9898    0.9979    0.9939       974
           9     0.9940    0.9871    0.9906      1009

    accuracy                         0.9930     10000
   macro avg     0.9930    0.9930    0.9930     10000
weighted avg     0.9930    0.9930    0.9930     10000



In [24]:
print(cm)


[[ 977    0    0    0    0    0    3    0    0    0]
 [   0 1131    2    0    0    1    1    0    0    0]
 [   1    1 1025    0    0    0    1    1    3    0]
 [   0    0    0 1004    0    4    0    1    1    0]
 [   0    0    0    0  978    0    1    0    1    2]
 [   0    0    0    4    0  885    2    0    0    1]
 [   2    2    1    0    0    2  950    0    1    0]
 [   0    6    6    0    1    1    0 1012    0    2]
 [   0    0    0    0    0    1    0    0  972    1]
 [   1    0    0    0    5    1    1    1    4  996]]
